service: serverless-api
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1
  timeout: 10

functions:
  graphql:
    handler: src/server.handler
    events:
      - httpApi:
          path: /
          method: "*"

    environment:
      SECRET: ${env:SECRET}

plugins:
  - serverless-plugin-typescript
